### ISSUE TITLE
Cannot run npm start.

### ISSUE THREAD

**Issue by yannisbarlas** [stencila/web#1]
I installed the application just fine, but I cannot run it. It crashes with 
```sh
/home/barlas/Downloads/code/stencila-web/node_modules/substance/util/SubstanceError.js:3
import oo from './oo'
^^^^^^
SyntaxError: Unexpected token import
```

I don't think es6 modules are supported in node yet.  
So maybe the new es6-based substance requires something along the lines of babel to work? 

I tried the ```--harmony``` flag on node, but it didn't make a difference.
I tried this on Ubuntu, node 6.6.0 / npm 3.10.3 .

**Comment by nokome** [comment]
Thanks for this @yannisbarlas - great to have some else try it out.

Yes, you're right Babel is required. It is already in stencila but there also needs to be browserify entry in substance's package.json. I have fixed that in my fork: https://github.com/stencila/substance/commit/60a30094d493a6bbfbfdc0a39c166a35b5fb28b6 which stencila uses.

So, it should work. Perhaps, I hadn't pushed changes when you tried. I just checked that this is working with a fresh copy of the repo:

```
git clone https://github.com/stencila/web stencila-web
cd stencila-web
npm install
npm start
```

Which works, but at time of writing, toolbar buttons are broken due to a recent Substance upgrade.

**Comment by yannisbarlas** [comment]
Ok, I got the latest code and that is no longer a problem.  
I still cannot run it though. I get errors in 'substance/ui/DefaultDOMElement'.
I'm assuming this will be fixed in the upcoming release of Substance Beta 5 .

**Comment by nokome** [comment]
Cool, thanks. Yes, there are a lot of breaks associated with the Substance move to ES6. Will wait until that is complete before trying to fix them.
